const Task = require('../models/Task');

const ownedTask = (id, userId) => Task.findOne({ _id: id, createdBy: userId });
async function listTasks(req, res, next) { try { const query = { createdBy: req.user._id }; if (req.query.status && req.query.status !== 'All') query.status = req.query.status; res.json({ tasks: await Task.find(query).populate('meetingId', 'title').sort({ createdAt: -1 }) }); } catch (error) { next(error); } }
async function getTask(req, res, next) { try { const task = await ownedTask(req.params.id, req.user._id).populate('meetingId', 'title'); if (!task) return res.status(404).json({ message: 'Task not found.' }); res.json({ task }); } catch (error) { next(error); } }
async function createTask(req, res, next) { try { const { title, description = '', owner, ownerEmail, deadline, priority = 'Medium', meetingId } = req.body; if (!title || !owner || !meetingId) return res.status(400).json({ message: 'Title, owner, and meeting are required.' }); const task = await Task.create({ title, description, owner, ownerEmail, deadline: deadline || undefined, priority, meetingId, createdBy: req.user._id, status: 'Pending' }); res.status(201).json({ task }); } catch (error) { next(error); } }
async function updateTask(req, res, next) { try { const task = await ownedTask(req.params.id, req.user._id); if (!task) return res.status(404).json({ message: 'Task not found.' }); Object.assign(task, req.body); if (task.status === 'Completed' && !task.completedAt) task.completedAt = new Date(); if (task.status !== 'Completed') task.completedAt = undefined; await task.save(); res.json({ task }); } catch (error) { next(error); } }
async function deleteTask(req, res, next) { try { const task = await Task.findOneAndDelete({ _id: req.params.id, createdBy: req.user._id }); if (!task) return res.status(404).json({ message: 'Task not found.' }); res.json({ message: 'Task deleted.' }); } catch (error) { next(error); } }
async function updateStatus(req, res, next) { try { const { status } = req.body; if (!['Pending', 'Assigned', 'In Progress', 'Completed'].includes(status)) return res.status(400).json({ message: 'Invalid task status.' }); const task = await ownedTask(req.params.id, req.user._id); if (!task) return res.status(404).json({ message: 'Task not found.' }); task.status = status; task.completedAt = status === 'Completed' ? new Date() : undefined; await task.save(); res.json({ task }); } catch (error) { next(error); } }
module.exports = { listTasks, getTask, createTask, updateTask, deleteTask, updateStatus };
